### PR TITLE
For Issue #27 - https://github.com/midwan/MB_SubSonic/issues/27

### PR DESCRIPTION
**Pull request by jalabulajunx**
Creating a workaround to retrieve Playlists as folders until MusicBee's owner Steven fixes a bug to relay calls for Playlists.

They would show like this - 

image

### CODE REVIEW

**Comment by midwan** [comment]
@jalabulajunx 
Let's wait a bit to see if Steven fixes this quickly, because then there's no need for this workaround. Otherwise we can merge it in and push a new version out of course.

**Comment by jalabulajunx** [comment]
I agree. My comments within the code reflects the same.

**Comment by jalabulajunx** [comment]
@midwan - I am unable to create another pull request on the fix for the NullRef issue #36. Should I target your dev branch instead of Master for the new pull request?

**Comment by midwan** [comment]
I think we can merge this instead, it doesn't look like Steve is coming back soon(ish)...

**Comment by jalabulajunx** [comment]
Alright! Thanks. I'll submit another one for the #36.

**Comment by jalabulajunx** [comment]
Done. Submitted another PR.

**Pull request merged**
